### ISSUE TITLE
Type Error with AutoGPT 0.3.1 

### ISSUE THREAD

**Issue by Monty1122** [riensen/Auto-GPT-Email-Plugin#20]
Anybody getting this with AutoGPT 0.3.1 - it was working with 0.2.2 for me..

Traceback (most recent call last):
  File "/Users/david/opt/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/david/opt/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/david/Desktop/dkautogpt/Auto-GPT-latest/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/david/Desktop/dkautogpt/Auto-GPT-latest/autogpt/cli.py", line 96, in main
    run_auto_gpt(
  File "/Users/david/Desktop/dkautogpt/Auto-GPT-latest/autogpt/main.py", line 127, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
  File "/Users/david/Desktop/dkautogpt/Auto-GPT-latest/autogpt/plugins.py", line 238, in scan_plugins
    loaded_plugins.append(a_module())
  File "/Users/david/opt/anaconda3/lib/python3.10/site-packages/abstract_singleton/__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
**TypeError: Can't instantiate abstract class AutoGPTEmailPlugin with abstract methods can_handle_report, can_handle_text_embedding, can_handle_user_input, handle_text_embedding, report, user_input**

**Comment by markesphere** [comment]
I ran into the same issue with the AutoGPT 0.3.1 update

**Comment by jinhongee** [comment]
Is there a way to solve this? Stuck on the same issue
